apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-aks
spec:
  selector:
    matchLabels:
      app: spring-boot-aks
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-aks

    spec:
      containers:
        - name: spring-boot-aks
          image:  springhelloacr.azurecr.io/springhello:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # The port that the container is running on in the cluster
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-aks
spec:
  selector:
    app: spring-boot-aks
   
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8082 # The port exposed by the service
      name: http
  type: LoadBalancer # type ospring-
  